//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCManukauTech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class premiumUser
    {
        public int primeId { get; set; }
        public string userID { get; set; }
        public System.DateTime endDate { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
