//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCManukauTech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int TransactionId { get; set; }
        public string UserName { get; set; }
        public string CardType { get; set; }
        public string CardHolder { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<bool> IsReserved { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> IsFulfilled { get; set; }
        public Nullable<int> NumberOfAttempts { get; set; }
        public Nullable<System.DateTime> DateOfReservation { get; set; }
        public Nullable<System.DateTime> DateOfFulfillment { get; set; }
    }
}
